name: trade
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  #ui https://pub-web.flutter-io.cn/packages/fluent_ui
  fluent_ui: ^4.9.0
  #路由 https://pub-web.flutter-io.cn/packages/go_router
#  go_router: ^14.2.0
  #主题 https://pub-web.flutter-io.cn/packages/system_theme
  system_theme: ^2.3.1
  #背景 https://pub-web.flutter-io.cn/packages/flutter_acrylic
  flutter_acrylic: ^1.1.4
  #状态管理 https://pub-web.flutter-io.cn/packages/get
  get: ^4.6.6
  #数据更新 https://pub-web.flutter-io.cn/packages/provider
  provider: ^6.1.2
  #屏幕适配 https://pub-web.flutter-io.cn/packages/flutter_screenutil
  flutter_screenutil: ^5.9.3
  #分屏 https://pub.dev/packages/multi_split_view
  multi_split_view: ^3.4.0
  #日志输出 https://pub.dev/packages/logger
  logger: ^2.3.0
  #color https://pub.dev/packages/hexcolor
  hexcolor: ^3.0.1
  #事件分发 https://pub-web.flutter-io.cn/packages/event_bus
  event_bus: ^2.0.0
  #右击菜单 https://pub-web.flutter-io.cn/packages/context_menus
#  context_menus: ^2.0.0+1
  super_context_menu: ^0.8.17
  #同步滚动 https://pub-web.flutter-io.cn/packages/linked_scroll_controller
  linked_scroll_controller: ^0.2.0
  #自适应文字大小 https://pub-web.flutter-io.cn/packages/auto_size_text
  auto_size_text: ^3.0.0
  #网路请求 https://pub.dev/packages/dio
  dio: ^5.7.0
  #toast https://pub.dev/packages/bot_toast
#  bot_toast: ^4.1.3
  #加密 https://pub-web.flutter-io.cn/packages/pointycastle
  pointycastle: ^3.9.1
  #SHA、MD5加解密 https://pub-web.flutter-io.cn/packages/crypto
  crypto: ^3.0.3
  #AES加解密 https://pub-web.flutter-io.cn/packages/encrypt
  encrypt: ^5.0.3
  #浮点运算 https://pub-web.flutter-io.cn/packages/decimal
  decimal: ^3.0.2
  #存储 https://pub-web.flutter-io.cn/packages/shared_preferences
  shared_preferences: ^2.3.1
  #protobuf https://pub-web.flutter-io.cn/packages/protobuf
  protobuf: ^3.1.0
  #WebSocket https://pub-web.flutter-io.cn/packages/web_socket_client
  web_socket_client: ^0.1.4
  #fixed-width 32- and 64- bit integer https://pub-web.flutter-io.cn/packages/fixnum
  fixnum: ^1.1.0
  #解压 https://pub-web.flutter-io.cn/packages/archive
  archive: ^3.6.1
  #时间选择 https://pub-web.flutter-io.cn/packages/omni_datetime_picker
  omni_datetime_picker: ^2.0.3
  #绘制虚线 https://pub-web.flutter-io.cn/packages/path_drawing
  path_drawing: ^1.0.1
  #表格 https://pub-web.flutter-io.cn/packages/pluto_grid
#  pluto_grid: ^8.0.0
  device_info_plus: ^10.1.2
  #本地通知 https://pub.dev/packages/local_notifier
#  local_notifier: ^0.1.6
  #webview https://pub-web.flutter-io.cn/packages/webview_windows
  webview_windows: ^0.4.0
  #表格 https://pub.dev/packages/scrollable_table_view
#  scrollable_table_view: ^2.0.3
  #翻页指示标 https://pub.dev/packages/smooth_page_indicator
#  smooth_page_indicator: ^1.2.0+3
  #屏幕尺寸 https://pub.dev/packages/screen_retriever
  screen_retriever: ^0.1.9
  #窗口管理 https://pub-web.flutter-io.cn/packages/window_manager
  #  window_manager: ^0.3.9
  window_manager:
    git:
      url: https://github.com/rustdesk-org/window_manager
  #多窗口 https://pub-web.flutter-io.cn/packages/desktop_multi_window
#  desktop_multi_window: ^0.2.0
  desktop_multi_window:
    git:
      url: https://github.com/rustdesk-org/rustdesk_desktop_multi_window
  uuid: ^4.5.0
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
      ref: a738913c8ce2c9f47515382d40827e794a334274
  flutter_rust_bridge: "1.80.1"
#  flutter_rust_bridge: ^2.7.0
  ffi: ^2.1.0
  win32: ^5.5.4
  path_provider: ^2.1.4
  url_launcher: ^6.3.0
  texture_rgba_renderer: ^0.0.16
  scroll_pos: ^0.5.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  intl: ^0.19.0
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0
  ffigen: ^8.0.2
  build_runner: ^2.4.6
  freezed: ^2.4.2
  flutter_launcher_icons: "^0.14.1"
  msix: ^3.16.8

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
dependency_overrides:
  uuid: ^4.5.0
#  uuid: ^3.0.7

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/
    - assets/images/
#    - assets/indicator/
    - assets/key/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
#msix_config:
#  display_name: "FCS.HK行情交易系统(模拟)"
#  publisher_display_name: "元泓"
#  msix_version: 1.0.0.0
#  logo_path: assets/images/jmaster.ico

flutter_icons:
  image_path: "assets/images/jmaster.ico"
  remove_alpha_ios: true
  windows:
    generate: true

msix_config:
  display_name: FCS.HK
  publisher_display_name: yuanhong
  msix_version: 1.0.0.0
  logo_path: "assets/images/jmaster.ico"
  install_certificate: true
  certificate_path: "assets/certificate/CertStoreLocation.pfx"
  certificate_password: 0000
#  app_installer: #<-- app installer configuration
#    publish_folder_path: E:\WorkPlace
#    hours_between_update_checks: 0
#    automatic_background_task: true
#    update_blocks_activation: true
#    show_prompt: true
#    force_update_from_any_version: false
